name: diaryschool
description: diaryschool for you.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  package_info: ^0.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  in_app_purchase: ^0.3.1+2
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  flutter_local_notifications: ^1.4.4+3
  url_launcher: ^5.4.1
  flutter_svg: ^0.18.0

  ext_storage: ^1.0.3
  permission_handler: ^5.0.0+hotfix.3

  path_provider: ^1.6.5

  equatable: ^1.1.1
  flutter_bloc: ^4.0.0

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  # Firebase
  firebase_core: "0.5.0"
  easy_localization: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  hive_generator: any
  build_runner: ^1.10.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/translations/
    - res/images/ic_launcher.png
    - res/images/logo1024x512.png
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
        - asset: assets/fonts/Raleway-Italic-VariableFont_wght.ttf
          style: italic
